### ISSUE TITLE
Episodes Order Bug?

### ISSUE THREAD

**Issue by gonzo90017** [fnord12/script.pseudotv#11]
This one has been around for a long time. The only reason I think it hasn't been noticed is that it only affects shows with 10 seasons or more. Or maybe it's my naming convention :)

Channel: **TV Show**
Sort Method (Episode); **Enable**
Instead of going from Season 1 to Season 2 To Season 3.  It goes from S1 to S10 then S2.
[Sort Method (Episode).zip](https://github.com/fnord12/script.pseudotv/files/4756042/Sort.Method.Episode.zip)

The only way to get the Seasons and episodes in order is by adding the Advanced Rule
**Play TV Shows in Order**
[Play Shows in Order.zip](https://github.com/fnord12/script.pseudotv/files/4756044/Play.Shows.in.Order.zip)

**Comment by fnord12** [comment]
That shouldn't be happening and i'm not able to replicate it.  This was actually my primary use case; i've got my Batman channel that plays episodes in order and i wanted to display the Episode names instead of the show title.

I thought maybe it was because you have that advanced rule that duplicates the play in order command, but i've tested with that and it still works fine for me.  I even tried it with a Force Resume rule since i know you use that.  Can you double check that you didn't change something for your channel to remove the ordering rules or something like that?

**Comment by fnord12** [comment]
I did find a quick and dirty way to deal with the season 10 problem.  I don't want to implement it but i'll tell you how.  In ChannelList.py, on line 1185 (currently), you'll see "epval = episode.group(1).zfill(2)".  That command is padding the episode numbers to two digits.  If you add that same .zfill(2) to the line above, i.e. "seasonval = season.group(1)" it will add two digits to the season number and then the seasons will be ordered the way they should be.  The reason i don't want to implement it is because it also affects the display, and for most people seeing 03x02 is just nonstandard and ugly.  (I could be convinced otherwise, i guess.)

**Comment by fnord12** [comment]
Also, in looking at the above, i realized that you renaming your seasons to have the leading 0s won't help.  At that stage, PSTV is getting the season info from the Kodi database via a JSON call.  It's just returning the numeric value.  So it doesn't matter how you labeled your files.

(This does lend argument to me needing to fix the issue, since one of the workarounds doesn't really work.)

**Comment by gonzo90017** [comment]
> That shouldn't be happening and i'm not able to replicate it. This was actually my primary use case; i've got my Batman channel that plays episodes in order and i wanted to display the Episode names instead of the show title.

If instead of using **Play Shows in Order** I use **Sort Method Episode** the episodes show up in order in the EPG. But then we go back to my original issue. 

This really isn't a big deal since most of my shows don't have 10 seasons. And this might be one of the only channels I would use this feature with. Since most of channels wiil be interleaved.

**Comment by fnord12** [comment]
Turns out there was a simple solution to the main issue.  It's now resolved in 4.5.1.
