### ISSUE TITLE
Don't include a show enhancement

### ISSUE THREAD

**Issue by gonzo90017** [fnord12/script.pseudotv#12]
Can we get a popup when choosing **Don't include a show** in advanced rules? It would be like the one you get when you make a channel based on a tv show.  In this example I tried adding **Teenage Mutant Ninja Turtles**

![Example](https://user-images.githubusercontent.com/24837361/84311931-fe2abd00-ab18-11ea-8e4c-eefad2b75adf.PNG)

It's working but once you click OK. Some of the characters are cut off.

**Comment by fnord12** [comment]
Does this Rule even work?  I spent some time (it took longer than it should have!) rewriting this as a select box instead of a text box.  But when I finished, I found that it wasn't working.  So I reverted the code and it seems like it still doesn't work.

For what it's worth, the reason it's truncating is because of line 443 in Rules.py "self.validateTextBox(0, 20)",  Change 20 to some larger number and it should stop getting cut off.

I generally find the Advanced Rules to be difficult to modify.  The code is pretty sophisticated, a lot of bitwise operations.  Much harder to check against than the normal Kodi add-on settings rules, and a bit out of my league.  I'm afraid to mess with them too much.

**Comment by gonzo90017** [comment]
It actually does work.. The only issue that I can see is what I mention above.

**Comment by fnord12** [comment]
This has been added to 4.5.2.  It doesn't work with custom playlists, which is mainly what i use and why i didn't think it was working before.  But i've confirmed that this works with regular channels, and now you don't have to type the name of the show.
