### ISSUE TITLE
Media playing from beginning

### ISSUE THREAD

**Issue by Tropps87** [fnord12/script.pseudotv#13]
On both my Windows and FireTV clients, every show or movie starts from the beginning when I switch channels. Doesn't matter if it should be a few minutes in or half way through a movie, it always resets to the beginning.

**Comment by fnord12** [comment]
What version of PSTV are you using?  What version of Kodi?  What mode(s) are you using (Realtime, Resume, etc.).

The problem of a channel restarting on STARTUP is a known issue.  4.5.1 seems to fix it for Realtime mode (but not Resume or Pause mode).  

But you're having the problem every time you change a channel?  If you're on 4.5.0 or 4.5.1 you might try increasing the Delay Before value under Performance.  You can also turn on debug mode and link me to the log (please follow the process for the Kodi log file linked to from my Troubleshooting.md file.).

**Comment by Tropps87** [comment]
How can I tell? The release notes and everything else just mention 2.5.0. I'm on Leia 18.7 and using Real-Time. I tried a fresh install and changing the Delay Before but no luck.

Here is a log file: https://paste.kodi.tv/ihilibatec.kodi

**Comment by fnord12** [comment]
Nothing definitive in the log, unfortunately.  Here is what i see:

1. I see one channel change in the log, from a family guy episode to a game of thrones.  It successfully seeks to position 1908.  There are a lot of "normal" messages after that talking about dropped packets and CheckContinuity.  ("normal" in the sense that i get them too, even when the seek is successful; i have no idea if those lines indicate a problem with the Kodi videoplayer).  What i see here is the same as what i see when the problem occurs for the starting channel - everything seems to seek to the correct point, and then the video mysteriously resets after that with nothing indicating it in the log.

2.  You are on 4.5.0 (i had a typo in the release notes that called it 2.5.0).  You might consider trying 4.5.1.  I wouldn't expect it to fix your problem entirely, but it MIGHT fix it for the starting channel, i.e. when you first start PSTV if it's not doing a channel reset.  IF it fixes it for that starting channel, i might be able to give you a patch that fixes it for the other channels.  (This is assuming that you are currently having a problem for the start channel too, i.e. when you first start PSTV it always starts at the beginning of a video, not where you left off + time passed).   To get the 4.5.1 branch select it from the branch dropdown on the Code tab before cloning the zip file.  Before that, though:

3. It looks like you are using Channel Sharing?  I've never tested with Channel Sharing and don't know if it affects things but there is extra processing involved when changing a channel, especially since you are also using network paths.  Have you tried with Channel Sharing turned off?

4. You are using a network share and are using a MySQL database.  If neither 4.5.1 or turning off Channel Sharing help, we may need to look into you doing a test with local files and/or with the stock database.

Tangentially:

5. You are running with restricted (non-Admin) rights, which may affect things relating to all the file-locking that happens with channel sharing.  There are a number of errors in the log like "error : 'open call failed with "NFS: Lookup of /PseudoTV/cache/channel_25.m3u failed with NFS3ERR_NOENT(-2)'".  They don't seem like they'd be related to your problem, and i don't know if you're having other issues related to Channel Sharing.  But i've generally found that Kodi works better when you run as an Admin, if you can.

**Comment by Tropps87** [comment]
Thanks for the large, awesome response! I wasn't aware of how to download 4.5.1 so thank you and that solved this issue. It no longer occurs.
