### ISSUE TITLE
On re-opening, video is paused

### ISSUE THREAD

**Issue by itsaNewBob** [fnord12/script.pseudotv#15]
Hello!

Very new here. All is working, but... if I move away from Kodi and re-open, the video is paused. Just need to hit play, but... Setting this up for my old man, so that won't fly!!
Android TV

Am I being daft?

**Comment by fnord12** [comment]
That's a new one to me.  There is of course the Advanced Rule to pause when not watching, but it sounds like you're not saying when you change channels, you're saying when you switch from Kodi to another program?  Does the same happen when just playing a regular video in Kodi?

If you can follow the steps to upload the Kodi log file linked to from my Troubleshooting.md file, I can possibly provide further information.  I'm going to be swamped for the next two days but will respond as soon as I can.

**Comment by itsaNewBob** [comment]
G'day!

Thanks for coming back so quickly, I will get a log file generated after work. Understand that you have a life outside of helping randoms like me - appreciate that you and the other contributors have got such a handy tool available!

**Comment by fnord12** [comment]
Hi (new!) Bob, are you still having the problem?  I wasn't sure I correctly understood the issue.  It sounds like when you click away from Kodi to another program, the video playing in PSTV gets paused?  If so, that may be an operating system issue that I'm not going to be able to help with.    If it's happening just in PSTV and not in regular Kodi, we can try to see what's different by looking at the log.  If at all possible, I would start very simple, with just a single channel and no advanced rules.  You can back up your current config - see the note at the bottom of the 4.5.0 release notes - so that you don't lose what you've set up for your father before trimming it back for testing.

**Comment by fnord12** [comment]
No response for over a month so i'm going to close this.
