### ISSUE TITLE
Channel bugs not working on FireTV

### ISSUE THREAD

**Issue by Tropps87** [fnord12/script.pseudotv#16]
We had chatted about this a little bit in a previous bug but I can not get channel bugs to work on my Amazon FireTV clients. I tried your suggestion of changing the Globals.py but that didn't work. I also tried generating them on my Windows client and copying them into the ChannelBug folder but they still wont load. They all just show the generic PseudoTV bug. The logos load and work fine in the EPG, though.

Here is a log file: https://paste.kodi.tv/ojicewuxin.kodi

**Comment by fnord12** [comment]
Two questions: Did this issue only start happening with my build(s)?  Did this issue only start after you updated the path for the logos the previous issue/question you posted?

The code that sets the channel bug is in a Try/Except loop.  That means that it will try to run code but if it runs into any exception error, it will instead perform a default action.  In this case that is setting the default logo bug.  The benefit of a Try loop is that it prevents the whole program from crashing over a minor issue, but the downside is it makes troubleshooting more difficult, since the error is just ignored/not written to the log.

I've created a Testing branch that takes the code out of the try loop.  Only one file has been changed: resources\lib\overlay.py 
So you can either clone the entire zip or just overwrite that file.  Can you please do that whichever way is easier and then run PSTV again in debug mode.  Most likely it will cause PSTV to crash and you'll have to shut Kodi down.  You can look at/copy the log before starting Kodi again, or if you do restart Kodi, you can grab kodi.old.log.

I expect that you'll see an exception error in the log (you can search for the word exception).  If you find one, it may show you your problem or you can paste just those lines directly here (i.e. no need to post the whole log to the pastebin again).  If you DON'T see an exception, search for the phrase "Image Path".  There should be two lines for each channel you've been on, showing us what it thinks should be the paths for the original and bug images.

Hopefully this will help us figure out what is going on.

**Comment by Tropps87** [comment]
Hey, thanks for the help! To answer your questions, channel bugs have never worked on my FireTV's. They didn't work with Steve's build., yours, or either modulations to the Globals file. Here is the exception that is getting thrown:

2020-06-29 16:24:55.599 T:11042   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 22] Invalid argument
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 271, in onInit
                                                self.setFirstChannel(self.currentChannel)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 442, in setFirstChannel
                                                self.showChannelLabel(self.currentChannel)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 724, in showChannelLabel
                                                self.setChannelBug()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 781, in setChannelBug
                                                converted_img = original.convert('LA')
                                              File "/data/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/Image.py", line 833, in convert
                                                self.load()
                                              File "/data/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/ImageFile.py", line 195, in load
                                                seek(o)
                                            IOError: [Errno 22] Invalid argument
                                            -->End of Python script error report<--

**Comment by fnord12** [comment]
It's failing in the Python Imaging Library (PIL), which is a standard Python module included with Kodi's Python and which is used by PSTV to manipulate the color logo into the watermark.  Since it's not failing in PSTV's code, my first thought is that the PIL module is somehow out of date.  Which doesn't make sense to me; PSTV asks to import a specific version (1.1.7) and either it should be there or not.  It shouldn't just try to run a different version and then give that invalid argument error.  But there may be something related to the FireTV OS; in random googling, i found cases where people on Android devices didn't have the module installed at all.

If this doesn't trigger something for you ("Aha! I know how to flush and update that module!"), i can ask on the Kodi forum.  But the PIL is just a black box to me; PSTV just calls it and it does its thing.

It probably won't be fruitful, but in the meantime if you want to experiment you could try using the new PSTV setting under Visuals>Color Watermark.  That's assuming that it's something specific in the original.convert('LA') line that is causing the problem. If you look at Overlay.py, that setting will instead trigger line 779 instead of 781.  You could also (instead) try changing line original.convert('LA') to original.convert('L') or  original.convert('1').  Dropping the A would mean not trying to affect the alpha value, the 1 would try converting to pure black & white instead of monochrome.  I don't know that any of this would matter; it's just an attempt to try to get around whatever is causing the error in PIL.  I think most likely i will have to ask on the forum.

**Comment by Tropps87** [comment]
Well, I tried the Color Watermark setting and modifying the original.convert to both an L and 1 and it still doesn't work so your assessment makes sense (as far as my understanding of all this). If you can ask in the forums for help, that would be most appreciated. 

Another thought, is there a code change I can make so it just looks to ChannelBug folder for the files? Then I could just generate the images on my Windows client and copy them over instead of relying on the PIL to modify the logo.

**Comment by fnord12** [comment]
I've updated the Testing branch with a new Overlay.py that should skip trying to use PIL and will just use existing watermarks if it finds them.

I've also posted a request for help here: [https://forum.kodi.tv/showthread.php?tid=355592](https://forum.kodi.tv/showthread.php?tid=355592)

If anyone is willing to help, they may want to see a full debug log with you starting Kodi fresh so that they can see all the versions of your plug-ins and such.  You may want to preemptively generate that before updating with the latest Overlay.py.

**Comment by Tropps87** [comment]
Using that new Overlay file works perfectly! Thank you! Feel free to close this out now as this is exactly what I need but I understand if you want to keep it open for tracking.

**Comment by fnord12** [comment]
If I do another release (no immediate plans!) i'll incorporate this code into the Try/Except loop so that if there's an error like you're experiencing it'll still try to look for local files before giving up and using the generic logo.  That way you'll be able to take any new updates.

**Comment by fnord12** [comment]
Hey Tropps87, we finally got a response on the Kodi forum post.  They link to another post, here: https://forum.kodi.tv/showthread.php?tid=356344&pid=2999095#pid2999095

I know we found a workaround for you, and what they've posted also seems to be a workaround (albeit possibly one that doesn't require manual intervention), so let me know if you need me to pursue this fix or if you're good.
