### ISSUE TITLE
Pulling logos from shared drives

### ISSUE THREAD

**Issue by Tropps87** [fnord12/script.pseudotv#2]
It'd be awesome to be able to point to a shared drive for logo storage like we can for sharing channels.  Currently it only allows local storage of logos.

**Comment by fnord12** [comment]
You should be able to do this now with a little finessing.  Find your userdata folder:
https://kodi.wiki/view/Userdata#UserData_folder_contents

In that, find your addons_data folder for PSTV, and in that find setting.xml.  Find the ChannelLogoFolder tag.  You can replace the value ("special...") with your path.  Or just input a hardrive path like "C:/".  Then the next time you go into the settings, you'll be able to navigate to the network path same as you can for channel sharing.

The control for the two fields is the same, the problem is that the Logo folder defaults to the "special" value, and you can't get "up" from special to the network shares.  But if you have a regular drive path, you can.

**Comment by Tropps87** [comment]
Thank you! I will give that a try.

One follow-up question: Does PseudoTV look to different locations for the logos in the EPG and the watermarks? On my FireTV the logos in the EPG work just fine but I still get the generic PseudoTV logo for all channels as a watermark.

**Comment by fnord12** [comment]
Yes, the logos are stored based on the above setting.  The Watermarks are always stored at \userdata\addon_data\script.pseudotv\cache\ChannelBug

Here's how to find your userdata folder, if you don't know:
https://kodi.wiki/view/Userdata#Location_of_the_userdata_folder

It's weird that the Watermarks aren't being generated if your logos are displaying.  In the folder above ChannelBug, you should also see a number of .m3u files corresponding to your channels.  Are those being put there?

**Comment by Tropps87** [comment]
The ChannelBug folder is empty. The main cache folder does have all the .m3u files but for some reason it still shows the generic PseudoTV bug. This is happening on two FireTV's but on my Windows PC the bugs display just fine.

**Comment by fnord12** [comment]
It does seem like some kind of access/path issue.  It sounds like this was happening even before you changed the main logo path?

You could always manually drop the logos in that folder (let them generate on the Windows machine and then copy them?)

Or if you want to try to play with the code, find globals.py and back it up and then look at CHANNELBUG_LOC and compare it to the other location variables.  I don't see why that one would fail when the main cache one is fine.

I wonder if this would work:

CHANNELBUG_LOC = os.path.join(SETTINGS_LOC, 'cache' + '/' + 'ChannelBug' + '/')
