### ISSUE TITLE
Specific show not showing up

### ISSUE THREAD

**Issue by Tropps87** [fnord12/script.pseudotv#26]
For some reason PseudoTV no longer will include any of my episodes for Gilmore Girls. It used to and I hadn't made any changes. They play inn Kodi just fine. And they show up in the playlists that the channels are pulling from just fine. When I check the logs I see a bunch of warnings about being unable to find the duration for the files. Any ideas how to resolve this? Thanks!

**Comment by fnord12** [comment]
Sorry you're having trouble.  There IS a longstanding problem where PSTV won't play videos if it can't find the duration of them, even if they play in Kodi, and in my 4.5.0 releases I added a bunch of options to try to get around the problem.  So under PSTV Settings > Performance you can cause ia default duration to be assigned when it's not finding one.  Normally I would say that would definitely help as a workaround, and the real solution is that there's an encoding problem with your files that can be fixed by running them through MKVToolNix or  ffmpeg or something.  

But it's weird that you just starting having the problem, which means that something else might be going on instead.  I assume you've confirmed that there aren't issues relating to access of the file (Drive letter change, network intermittency, etc.) especially since they still play fine in Kodi.  Any special channel rules that affect the channel that should be playing these episodes?  Like Play Only Un/Watched, which might cause the episodes to start off in the playlist but then get skipped?  Can you try making a channel with just these episodes, turn on debugging, and do a Force Channel Reset and upload the log (follow the instructions linked to in the troubleshooting doc)?

**Comment by Tropps87** [comment]
This was helpful, thanks! Tossing the files in MKVToolNix has helped solve the problem.
