### ISSUE TITLE
Channel configuration directory issue

### ISSUE THREAD

**Issue by Domjen2521** [fnord12/script.pseudotv#37]
@fnord12 Im new to PseudoTv, I like this version alot. I have old boxes and this one works the best on them. I was wondering if there was a way to add or modify the code to allow for channel configuration to show the directory option as the SMB network option to choose the directory that way instead of internal on system. Im attempting to make two channels that the directory contents are on a network drive. this is to be able to allow the other two boxes in my house to pick them up. When i do internal directory, no matter how its setup it causes kodi and the guide to freeze.

**Comment by fnord12** [comment]
Hi @Domjen2521  I don't have a lot of experience with SMBs personally.  In the past people have reported having problems with SMBs and have used a workaround to map their SMB shares to network drives.  There's info about that in the Readme.md under Tips & Tricks.  But you seem to be having the opposite problem where your SMBs work but your drives don't. 

I'd like to at least see in your log if there's a reason why Kodi is freezing.  I will look at your log if you can enable debugging and put it on a pastebin site - instructions for all that here: https://kodi.wiki/view/Log_file

If we don't see anything in there we can try manually updating your settings2.xml file.  That file can be found at \userdata\addon_data\script.pseudotv\settings2.xml    Here's how to find your userdata folder, if you don't know:
https://kodi.wiki/view/Userdata#Location_of_the_userdata_folder

What I would do is find one of the directory channels in that file and update the path to the SMB path instead of the local path.  But let's see if there's anything in the logs first.

**Comment by Domjen2521** [comment]
Hello @Fnord12, I have the external usb drive setup as a network drive letter h. It seems upon further investigation that the guide itself will still freeze without the smb drive setup. when the smb is setup and added to the guide it makes an event log of failure when attempting to select the channel. This is before the guide randomly freezes. if im quick i can select it. The log provided is the one with the event log of failure. i have other logs if needed. most are windows based. but i have one that is android if needed.

https://paste.kodi.tv/ovaligecid.kodi

**Comment by fnord12** [comment]
Sorry for the long delay!

I do see the failure to get the H drive.   It would be dumb, but I wonder if the apostrophe in the directory path might be a problem.  If it's easy, can you try removing that?

However, I wouldn't expect that to cause the EPG to freeze.  And from what you say, it happens whether or not you're trying to use the H drive.  Usually the EPG gets laggy if it has to render lots and lots of boxes/episodes.  I've seen happen where someone has a lot of interlaced commercials between episodes and it just becomes too much for the EPG to render.  There are some ways to deal with it - see the [Hide Short Videos option as described here](https://github.com/fnord12/script.pseudotv/issues/9), for example.  But it might be better (if very annoying and tedious) to start from scratch, just create one channel, see if the EPG locks up, and then keep adding until you can isolate if it's a specific channel that's causing the problem.  You only have 45 channels overall, not a lot, so that alone shouldn't' be the issue, but it's possible that a particular type of channel is causing the problem.

I also see a minor error for Reset Watched which shouldn't be related to the lag and we can look into that if we get the other issue addressed.  I would say disable that feature in the meantime but that will cause PSTV to start marking things as watched and updating the start points, so if that will bother you (it would bother me!) leave it on for now and we'll see if anything else helps first.

**Comment by Domjen2521** [comment]
No problem on the waiting. i reinstalled kodi on two machines to start from scratch. the main one running the stuff and the secondary one trying to view. both are windows 7. it is mostly random. I have only 3 channels and when i pop up the guide, it will freeze while pulled up. Sometimes it freezes and the guide doesnt even pop up or shows up as a blank guide, even though the video continues to play. the only way to exit when these things happen is to force shutdown the kodi app. below is the log.

https://paste.kodi.tv/abuhideqez.kodi

**Comment by fnord12** [comment]
It's difficult to troubleshoot.  No errors in the current log.  The log shows button pushes in the EPG ("CInputManager::HandleKey: up (0xf080) pressed, action is Up") that makes it look like things are running normally.  And at the end of the file it looks like things exited properly with the skin getting Deint-ed.

I don't use the channel sharing feature and I'm not that familiar with it, so if you're able to turn that off for the moment and just try on your main computer to confirm that alone causes the freeze, it would help.   I also normally use the Confluence skin which means that the PSTV skins I'm using are in the /resources/skins/default/1080i/ folder whereas you are using the /resources/skins/skin.estuary/xml/ folder.  (The file in both cases is EPG6.xml.   I've tested with Estuary in the past and didn't run into issues but it may be there's something with the Estuary version that is causing a problem.

I'm really just grasping at straws, trying to find things different than my setup, since I also have it running on a Win7 machine and it works fine.  Usually when the EPG completely locks up or disappears and then Kodi becomes unresponsive, there's an ERROR: in the log that shows up to explain the crash.   And if it's not a crash it would be a performance issue but if you're testing with just 3 channels (and presumably not a million ~1 minute shows or something; it doesn't look like that).

Sorry I'm not able to help more but I'm happy to keep looking at log files if you try things that produce different results.

**Comment by Domjen2521** [comment]
The main unit, works fine no issues at all. its the secondary one with the guide freezing. i have included another log here. I changed to the other skin but still the same issue.  The first log is a random freeze n crash. The second log is the guide popping up but freezing with no items showing, video still playing, the only way to exit is to force shutdown the program. i hope something comes up. for the second log, i got this kodi_stacktrace-18.9 Git_20201023-0655c2c718-20220722-123620 message in a file with a dump file. the txt has this message inside it. 

Thread 5748 (process 6848)
# 0


https://paste.kodi.tv/nayavimida.kodi

https://paste.kodi.tv/asibuwuliz.kodi

**Comment by fnord12** [comment]
Thanks.  I don't know how to interpret the stacktrace file, but there are some good meaty errors in the two logs. 

In the first one (nayavimida.kodi), the first relevant* error is "ERROR: script.pseudotv-ChannelList: Unable to locate the playlist for channel 1", and then you can find the same for channels 2 & 3, and then the real errors start.  It seems like on this box it is not seeing the shared channel folder.  This is the path that you set in the Shared Channels Folder in the PsTV settings.  It seems what you're setting there isn't accessible or visible by the second computer.  It might be a permissions error or something like that.  I know your original post was about getting the 2nd computer to see the directory channel content, but it may be just about getting the computer to see the playlists at all?  I don't have personal experience with the channel sharing but there is something in the readme that people have used when having trouble.   You may also want to look at the technique used in this issue (in that case it was about the channel logos but something similar may work if normal ways of setting the shared folder aren't): https://github.com/fnord12/script.pseudotv/issues/2

The second log shows an issue where it isn't seeing certain items in the EPG6.xml file.  For example you'll see "Non-Existent Control 113" and similar, even though items with value id="113", etc., are in the EPG6.xml file.  That says to me that the EPG just isn't being created probably due to the above shared folder issue.  So I'd say focus on the shared folder issue first.

*there are first some general Kodi errors that may relate to that directory channel: "ERROR: XFILE::CDirectory::GetDirectory - Error getting addons://sources/" and "ERROR: CGUIMediaWindow::GetDirectory(addons://sources/) failed".  If that is about the directory channel, it alone shouldn't cause PsTV to fail.  But you may want to look at your current video sources and remove any for now that might be causing the problem.

**Comment by Domjen2521** [comment]
Ok here goes, i reduced everything to just access one directory. 64 movies in it. no more. it works fine, channels change, everything. i add a second directory. which is 600 more movies. and the guide starts to freeze and act up on the secondary pc. is there a limit to the size of directories? I cant find any information on that, if it is not a directory limit size, then it is something with one of the files. im gonna make another directory and limit the files on it and see if it works or causes the same issue. Also a note, i moved the shared channel list to the drive itself on smb aka easier to find. Update#2 - I have narrowed down the issue of sorts, troubleshooting and testing to see if it works or can be repeated. it seems that kodi is quite picky when it comes to scraping movies and adding them, kodi doesnt list all the movies on the smb drive, but the addon sees the movies and shows that do not pop up causing a discrepancy, hence the guide issue.

**Comment by fnord12** [comment]
There is a limit option in PseudoTV but it doesn't apply to custom playlists or directories.  Custom playlists can be limited as part of the playlist definition.  But directories can't be limited.  I've looked into trying to get the code to apply the limit to the directory but it's trickier than I hoped, and also most people use directories for small files that Kodi won't scrape - mostly for commercials and bumpers, also for short videos like music videos (although I personally prefer to let Kodi scrape the music vids too).   The point being that usually you wouldn't want to apply the same limit to Directories as other channel types.  If that second directory is full of "real" movies (e.g. movies that could be scraped via TMDB) I would recommend letting Kodi scrape them - not only will you then be able to create channels with limits but you'll get to see all the movie's metadata when running PsTV.  Of course I know that there are reasons why not everyone scrapes the movies so if that's not possible we can try to find something else.

P.S. If you are scraping, the Event Log in Kodi should show which videos are not getting scraped properly.

That said, if you're setting up the 2nd channel as a Directory channel, PsTV shouldn't really care if Kodi recognizes the movies or not.  PsTV should just try to play them without metadata, and if it can't play a video or something it should just skip it, and there's also an option to assign a default length to the movie if it can't determine it.   But clearly you've narrowed down the problem and seem to be on a right track, so there may be something I don't know.

**Comment by Domjen2521** [comment]
Sometimes, the kodi just doesnt want to scrape a show here or there that exists on the tvdb, but for some reason just doesnt want to. i just removed it because even the tiny media manager couldnt get info (without paying for the pro subscription). Heres the resolution. make sure all shows are scraped. either by kodi, or mezzmo, or tiny media manager. once all scraped. the guide hanging will go away. I also manually added the directorys as smb replacements in the settings2.xml file as stated in the readme and that fixed the issue of the rejecting the channels. a new issue popped up but im still investigating, it is not related to these issues. so ill close this one out and try to see if i can replicate the other one. ty for your help.
