### ISSUE TITLE
Channels missing from Guide

### ISSUE THREAD

**Issue by Domjen2521** [fnord12/script.pseudotv#38]
I currently have 62 viewable channels. and 11 hidden channels for bumpers and commercials. On the main machine they work fine. On the secondary machine, the channels play fine, except for an error here or there about directory channel possibly failed to load a video (not the issue). The issue i am having is this, the guide will show all the viewable channels for a few seconds then it randomly pics what channels to list, each time i load it up, its a different set. one time only channels 1 through 33 appeared. another time only 24 through 58 appeared. you could even be like say channel 4 and the guide pulled up and channel 4 will disappear from the guide. its mostly random at this point and cant figure out why. i have included a log to see if anyone can spot an issue.

https://paste.kodi.tv/kobayakipi.kodi

**Comment by fnord12** [comment]
I'm seeing two types of file access errors in the logs.   The first are explicitly unix errors when trying to access the playlists.   Example:
2022-09-17 14:25:30.847 T:4613   DEBUG: CSMBFile::Open - opened smb://MINGOSERVER/Media/Channels/cache/channel_999.m3u, fd=-1
2022-09-17 14:25:30.847 T:4613    INFO: SMBFile->Open: Unable to open file : 'smb://MINGOSERVER/Media/Channels/cache/channel_999.m3u'
                                            unix_err:'16' error : 'Invalid argument'

It's weird to me because I think in some cases these are for channels you probably haven't even configured - channel 999 in the above example.

The other type of error is more of a direct PseudoTV error but same kind of thing:

Line 27595: 2022-09-17 14:26:02.981 T:4613   ERROR: script.pseudotv-ChannelList: Unable to locate the playlist for channel 68

The following channels had the above kind of error: 1,2,3,4,5,6,7,8,10,11,12,13,14,15,61,62,63,64,68  This probably corresponds to the channels that were missing.   It's possible that the first kind of error is causing the second but it's not consistent (e.g. channel 68 seems to open fine in the initial cache/channel area but then fails in the line above).  Which suggests some kind of intermittent access issue?   This may be why in your example channel 4 initially appears and then disappears.

The other thing is I see you have a lot of Do Not Include Show options.  That should be fine, but I have accidentally excluded so much from a channel that nothing loads (for me it's when I exclude Unwatched shows but the same thing could happen with the Do Not Include Show option).  This is PROBABLY not the issue but just wanted to raise the possibility.

**Comment by Domjen2521** [comment]
Yea, i have a lot of "do not include", only because i am creating a custom channel of cartoons and specific shows. that was another thing, is there a manual way to do a "include only the following shows" type script? that might fix most issues. the other thing, my bumper and commercial channels are in the 190s because it was easier to separate them far apart. Im thinking now that it may have to do with the excluding of shows that is causing the error. Channels 1,2 and 6 have a lot of exclusions. channels 61-64 and 68 are my saturday morning stuff. these have the bumpers and commercials with them. these also have a lot of exclusions since i set them up as abc cbs nbc saturday morning cartoons only. also two other unique channels, abc tgif and tnbc.  Im gonna try to move my channel list to another network drive and see if its an intermittent network issue im not picking up. I definitely did not use channel 999. my channels only go up to 200 max. thats how i listed it. Im gonna look into the list as well and see what channels are listed that should not be there. ty for the help. so close to getting it to work badass on another system like real cable tv lol

UPDATE - 
I moved the list of channels made, to a flash drive that is direct to the router. the issue still occurs. the channels will appear all properly on first run, then randomly disappear. im going to try to do a temp mini setup and see if the issue occurs if everything runs off the hd that is on the router usb plug.

**Comment by Domjen2521** [comment]
I have created a basic 10 channel set. the drive channels and the list are all running from the router directly. no slow down no interference. I still get the issue where the channels randomly do not appear. right away channel 1 does not pop up, after a few minutes a few more disappear. There are no restrictions on the channels at all. no shows blocked. just a few episodes for each station to test. here is the log. any help on figuring this out is appreciated. thank you again.

https://paste.kodi.tv/akafizofeb.kodi

**Comment by fnord12** [comment]
Sorry for the long delay again.

Is this still with channel sharing?   I'm afraid I don't know enough about it to really get into the details.   One thing I see early in the log is an error like this: 

2022-10-04 21:49:39.291 T:4547   DEBUG: CSMBFile::Open - opened smb://MINGOROUTER/sda1/Channels/cache/channel_0.m3u, fd=-1
2022-10-04 21:49:39.291 T:4547    INFO: SMBFile->Open: Unable to open file : 'smb://MINGOROUTER/sda1/Channels/cache/channel_0.m3u'
                                            unix_err:'2' error : 'No such file or directory'

There's an error like that for every channel from 0 to 999 (you might slightly improve your start performance by adjusting the value under Performance > Max Needed Channels, but that's not important or causing the problem).   It seems to continue on despite those errors, possibly it is finding no directory on the 2nd TV instance and then imports it from the shared directory.   In which case the above errors are OK.  I am not sure.   But then later I see this kind of error:

2022-10-04 21:49:47.078 T:4615   ERROR: script.pseudotv-ChannelList: Unable to locate the playlist for channel 1

And then the same kind of error a little later:

2022-10-04 21:50:07.229 T:4615   ERROR: script.pseudotv-ChannelList: Unable to locate the playlist for channel 2

So I don't know if the difference between those timestamps is how long it takes for your channels to disappear.  Like you see channel #1 until that first " Unable to locate the playlist" error appears, and then channel #2 appears after the 2nd.

It would really require analyzing your actions while the debug is running against the timestamps; maybe you can narrow down the specific error based on that.  You might play with the setting at General > Background Updating just to see if it helps.

Sorry I'm not able to just directly find the problem.

**Comment by Domjen2521** [comment]
Not a big deal, been messing with it to see what i could narrow down. Im going to do the full processing and see if it comes up and fixes issues. its going to take me a bit to fully test it. will post as soon as possible.

**Comment by Domjen2521** [comment]
So i went to town and messed with stuff. i put the full function of background updating, it shows it adding channels. but again they just randomly disappear. i dont know what it is. for now ill just stick to one tv until i can figure this out. thank you for all your help though, it is greatly appreciated more than i can say.
